
set(CMAKE_REPO_URL https://github.com/Eyescale/CMake.git)
set(CMAKE_REPO_TAG master)

set(CMAKE_EXTRA
  CONFIGURE_COMMAND touch ${CMAKE_BINARY_DIR}
  BUILD_COMMAND touch ${CMAKE_BINARY_DIR}
  INSTALL_COMMAND touch ${CMAKE_BINARY_DIR}
)
