
set(EQDOCS_REPO_URL https://github.com/Eyescale/EqDocs.git)
set(EQDOCS_REPO_TAG master)
set(EQDOCS_NOTEST ON)
set(EQDOCS_OPTIONAL ON)

set(EQDOCS_EXTRA
  CONFIGURE_COMMAND ${CMAKE_COMMAND} -E touch ${CMAKE_BINARY_DIR}
  BUILD_COMMAND ${CMAKE_COMMAND} -E touch ${CMAKE_BINARY_DIR}
  INSTALL_COMMAND ${CMAKE_COMMAND} -E touch ${CMAKE_BINARY_DIR}
)
