set(OPENSCENEGRAPH_PACKAGE_VERSION 3.0)
set(OPENSCENEGRAPH_REPO_URL https://github.com/openscenegraph/osg.git)
#set(OPENSCENEGRAPH_REPO_TAG OpenSceneGraph-3.1.2)
set(OPENSCENEGRAPH_CMAKE_ARGS -DCMAKE_OSX_ARCHITECTURES=i386
  -DCMAKE_BUILD_TYPE=Release)
set(OPENSCENEGRAPH_NOTEST ON)
set(OPENSCENEGRAPH_OPTIONAL ON)
set(OPENSCENEGRAPH_ROOT_VAR OSG_DIR)

# OS X 10.8 hotfixes
set(OPENSCENEGRAPH_USER_URL https://github.com/BlueBrain/osg.git)
