set(QT_STEERER_VERSION 3.5.1)
set(QT_STEERER_DEPENDS Boost Lunchbox steer_lib Qt4 Qwt)
set(QT_STEERER_REPO_URL https://github.com/BlueBrain/qt_steerer.git)
set(QT_STEERER_REPO_TAG master)
set(QT_STEERER_NOTEST ON)
