
set(REALITYGRID_VERSION 3.5.1)
set(REALITYGRID_DEPENDS REQUIRED LibXml2 XDR ZLIB)
set(REALITYGRID_REPO_URL https://github.com/BlueBrain/steer_lib.git)
set(REALITYGRID_REPO_TAG master)
set(REALITYGRID_NOTEST ON)
set(REALITYGRID_OPTIONAL ON)
set(REALITYGRID_SOURCE "${CMAKE_SOURCE_DIR}/src/steer_lib")
